name: Check

on: [push, pull_request]

jobs:
  build:
    name: Check and lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pipx install poetry
        poetry install

    - name: Typecheck code
      run: poetry run mypy dns

    - name: Check domains
      run: poetry run python -m dns.lint
