name: Update DNS

on:
  push:
    branches:
    - dev

jobs:
  make_doc:
    name: Update DNS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pipx install poetry
        poetry install

    - name: Update DNS
      run: poetry run python -m dns.sync
      env:
        PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
        PORKBUN_API_SECRET: ${{ secrets.PORKBUN_API_SECRET }}
